name: YptMC
version: '1.2'
main: me.lucwallace.yptmc.YptMC
api-version: '1.21'
authors: [ Luc Wallace ]
commands:
  ypt:
    description: YeolPumTa integration
    usage: /ypt time, /ypt register <player> <ypt_id>, /ypt status, /ypt group
